"use client";

import { motion } from "framer-motion";
import { useInView } from "react-intersection-observer";
import { Brain, Lightbulb, Clock, Sparkles, CheckCircle } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI Learning Summary",
    description: "Get 3 bullet points of what you learned so far, instantly generated by AI.",
    color: "#00f5ff",
  },
  {
    icon: Lightbulb,
    title: "Next Tiny Step",
    description: "AI recommends your next micro-action to keep momentum going.",
    color: "#a855f7",
  },
  {
    icon: Clock,
    title: "10-Minute Mode",
    description: "Focused micro-lessons that fit into any schedule.",
    color: "#f472b6",
  },
  {
    icon: Sparkles,
    title: "Why This Matters",
    description: "Confidence boosters explaining the relevance of each module.",
    color: "#22c55e",
  },
];

const platforms = ["Udemy", "Coursera", "YouTube", "Notion", "Bootcamps"];

export function MicroIntelligence() {
  const { ref, inView } = useInView({
    threshold: 0.2,
    triggerOnce: true,
  });

  return (
    <section id="features" className="py-24 relative overflow-hidden" ref={ref}>
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#00f5ff]/5 to-transparent" />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium bg-[#00f5ff]/10 border border-[#00f5ff]/20 mb-4">
            <Brain className="h-4 w-4 text-[#00f5ff]" />
            Micro-Intelligence Layer
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
            <span className="gradient-text">Smart Learning</span> Assistance
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            AI-powered micro-intelligence that understands your learning journey and guides you forward.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group"
            >
              <div className="h-full p-6 rounded-2xl bg-card border border-border hover:border-[#00f5ff]/50 transition-all duration-300 hover-lift dark:glass-card">
                <motion.div
                  className="w-14 h-14 rounded-xl flex items-center justify-center mb-4"
                  style={{ backgroundColor: `${feature.color}15` }}
                  whileHover={{ scale: 1.1, rotate: 5 }}
                >
                  <feature.icon
                    className="h-7 w-7"
                    style={{ color: feature.color }}
                  />
                </motion.div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="relative p-8 rounded-3xl bg-gradient-to-r from-[#00f5ff]/10 via-[#a855f7]/10 to-[#f472b6]/10 border border-[#00f5ff]/20 dark:neon-border"
        >
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
              <h3 className="text-xl font-semibold mb-2">Works Everywhere via Browser Extension</h3>
              <p className="text-muted-foreground">Install once, learn smarter on all platforms.</p>
            </div>
            <div className="flex flex-wrap gap-3 justify-center">
              {platforms.map((platform, index) => (
                <motion.span
                  key={platform}
                  initial={{ opacity: 0, scale: 0 }}
                  animate={inView ? { opacity: 1, scale: 1 } : {}}
                  transition={{ delay: 0.6 + index * 0.1 }}
                  className="px-4 py-2 rounded-full text-sm font-medium bg-background border border-border flex items-center gap-2"
                >
                  <CheckCircle className="h-4 w-4 text-[#22c55e]" />
                  {platform}
                </motion.span>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
